name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to create release for (e.g., v1.2.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string
        default: ''
      # values_dir:
      #   description: 'Values folder inside ArgoCD repo'
      #   required: false
      #   type: string
      #   default: 'poc-workflows-python-repo'

permissions:
  contents: write

jobs:
  create-release:
    uses: gocloudLa/poc-workflows-shared/.github/workflows/create-release.yml@main
    with:
      tag_name: ${{ inputs.tag_name }}
      release_notes: ${{ inputs.release_notes }}
      values_dir: 'poc-workflows-python-repo'
    secrets: inherit
