name: "Develop Push Events Workflow"

on:
  push:
    branches: [develop]

permissions:
  pull-requests: write
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  develop-push-events:
    uses: gocloudLa/poc-workflows-shared/.github/workflows/shared-develop-push-events-python.yml@main
    with:
      service_name: python-service
    secrets: inherit

  test-aws-oidc-action-2:
    name: test-aws-oidc-action-2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials using GitHub Action
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SHARED }}
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Test AWS S3 access
        run: aws s3 ls

  test-aws-oidc-action-3:
    name: test-aws-oidc-action-3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials using GitHub Action
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SHARED }}
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Test AWS S3 access
        run: aws s3 ls


