name: "Pull Request Events Workflow"

on:
  pull_request:
    branches: [develop, main]
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  pull-request-events:
    uses: gocloudLa/poc-workflows-shared/.github/workflows/shared-pull-request-python.yml@main
    secrets: inherit

  test-aws-oidc-action-1:
    name: test-aws-oidc-action-1
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials using GitHub Action
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::690282640967:role/dmc-lab-github
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Test AWS S3 access
        run: aws s3 ls
